#' -------------------------------------------------------------------------
#' Script to asses the best smooth window to use when calculating the
#' accelerometer's Dynamic Acceleration and VeDBA. Based on Shepard (2008).
#'
#' The value found here is the default value for the smoothing window in the DBA 
#' function.
#'
#' Based on the plot generated by this script the default smoothing window was 
#' set at 4 sec.
#' -------------------------------------------------------------------------
library(data.table)
library(tidyr)
library(zoo)
library(ggplot2)
library(dplyr)
library(patchwork)
source("utils/tuco_theme.R")

tuco = readRDS("data/tuco_10hz_smooth_subset.rds") # This is a subset of 4 animal/4 days
tuco[, day_number := NULL]
tuco[, datetime := NULL]

# Calculate VEDBA using different smoothing windows to subtract the static acceleration
windows = seq(from = 1, to = 12, by = 1)
for (i in windows) {
    tuco[, Xd := X - frollmean(x = X, n = i*10, align = "left"), by = ID]
    tuco[, Yd := Y - frollmean(x = Y, n = i*10, align = "left"), by = ID]
    tuco[, Zd := Z - frollmean(x = Z, n = i*10, align = "left"), by = ID]
    
    tuco[, paste0("vedba", i) := sqrt(Xd^2 + Yd^2 + Zd^2)]
    tuco[, c("Xd","Yd","Zd") := NULL]
}
tuco[, c("X","Y","Z") := NULL]

# Calculate mean VEDBA over 5 min
setkey(tuco, ID)
tuco3000 = tuco[, lapply(X = .SD, FUN = rollapply, width = 3000, by = 1000, median), by = ID]

# Transform wide dataset into long dataset
tuco3000 = pivot_longer(tuco3000, 2:length(tuco3000), names_to = "smooth", values_to = "vedba")

# Reorganize factor levels
i = seq(0, 12, by = 1)
tuco3000$smooth = factor(tuco3000$smooth,
                         levels = c(paste0("vedba", i)))

tuco_plot_5min = tuco3000 %>% 
    group_by(smooth) %>% 
    summarise(mean = mean(vedba, na.rm = T), n = n(), sd = sd(vedba, na.rm = T), se = sd/sqrt(n))

# PLOTS -------------------------------------------------------------------
plot_point = ggplot(na.omit(tuco_plot_5min)) +
    geom_pointrange(aes(y = smooth, x = mean, xmin = mean - sd, xmax = mean + sd)) +
    theme(panel.grid.major.x = element_line(color = "grey85", linetype = 3)) +
    scale_x_continuous(limits = c(-0.02,0.3)) +
    xlab("VeDBA") +
    ylab("Static Acc. Smoothing Window")

plot_boxplot = ggplot(na.omit(tuco3000)) + 
    geom_boxplot(aes(x = vedba, y = smooth)) +
    theme(panel.grid.major.x = element_line(color = "grey85", linetype = 3)) +
    scale_x_continuous(limits = c(-0.02,0.8)) +
    xlab("VeDBA") +
    ylab("Static Acc. Smoothing Window")

plot_smoothwindow = plot_point / plot_boxplot

ggsave("suplemental_info/06_smoothing_window/smoothing_window.png", plot_smoothwindow, "png", width = 9, height = 10, dpi = 150)
